apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongo-express-ingress
spec:
  tls:
    - hosts:
        - je.suce.ugur.gratuit.com
      secretName: je.suce.ugur-secret-tls
  rules:
    - host: je.suce.ugur.gratuit.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mongodb-express-service
                port:
                  number: 8081
#          - path: /bar
#            pathType: Prefix
#            backend:
#              service:
#                name: service2
#                port:
#                  number: 8080