name: Auto reviews release
on: pull_request
jobs:
  reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Auto reviews branches
        uses: golfzaptw/action-auto-reviews-from-branches@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          EVENT_TYPE: APPROVE
          BRANCHES: main
          AUTHOR: 'dependabot-preview[bot], dependabot[bot], damouu, github-actions, github-actions[bot]'
          MESSAGE: Nice approve from github bot.