name: 'Label Actions'

on:
  pull_request:
    types:
      - labeled

permissions:
  contents: read
  pull-requests: write

jobs:
  action:
    if: github.event.label.name == 'Staging'
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/label-actions@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          label: 'automerge'