name: Java CI with Maven

on:
  workflow_run:
    workflows: [ "automerge" ]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Docker Build and Push Action
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: damou/springdemo
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}