name: automerge
on:
  pull_request_target:
    types:
      - labeled
  status: { }
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: ${{ secrets.MyWorkflow  }}