name: automerge
on:
  workflow_run:
    workflows: [ "YouTrack-Staging" ]
    types:
      - completed
  check_suite:
    types:
      - completed
  status: { }
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: ${{ secrets.MyWorkflow  }}