name: automerge
on:
  pull_request:
    types:
      - edited
  status: { }
jobs:
  automerge:
    if: github.event.label.name == 'Staging'
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: ${{ secrets.MyWorkflow  }}