name: pull-request-responsibility

on:
  pull_request:
    types: [ assigned,opened,review_requested,ready_for_review,review_request_removed ]
  pull_request_review:
    types:
      - submitted
      - dismissed
      - edited
  public:
  pull_request_target:
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - ready_for_review
      - locked
      - unlocked
      - review_requested
      - review_request_removed


jobs:
  pull-request-responsibility:
    runs-on: ubuntu-latest
    name: pull-request-responsibility
    steps:
      - uses: actions-automation/pull-request-responsibility@main
        with:
          actions: "assign"
          token: ${{ secrets.GITHUB_TOKEN }}