name: Test

on:
  push:
    branches:
      - test

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build and created with Maven
        run: mvn -B package --file pom.xml
      - name: Create an issue
        if: ${{ failure() }}
        uses: JasonEtco/create-an-issue@v2.6.0
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: pull-request
        if: ${{ success() }}
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}