name: Test

on:
  push:
    branches:
      - test

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Set environment variables
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV

      - name: environment_variables
        run: echo "::set-output name=GITHUB_SHA_SHORT::$(echo $GITHUB_SHA_SHORT)"
        id: AWS

      - name: maven error tests messages
        run: echo "::set-output name=msg::$(mvn test -Dsurefire.useFile=false | grep 'ERROR' | head -4 | tail -1 | cut -d' ' -f2-)"
        id: mvn_test_error

      - name: maven error tests messages
        run: echo "::set-output name=msg::$(mvn test -Dsurefire.useFile=false | grep 'ERROR' | head -4 | tail -1 | cut -d' ' -f2- | rev | cut -c 35- | rev)"
        id: mvn_test_error_short

      - name: Runing Unit/ Integration Tests
        id: run_tests
        run: mvn test

      - uses: actions/checkout@v2
      - name: Create an issue
        if: ${{ failure() }}
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          actor: ${{ github.actor }}
          test: duplicate
          sha: ${{ steps.AWS.outputs.GITHUB_SHA_SHORT }}
          error: ${{ steps.mvn_test_error.outputs.msg }}
          error_short: ${{ steps.mvn_test_error_short.outputs.msg }}
        with:
          assignees: ${{ github.actor }}
          update_existing: true
          search_existing: open

      - name: pull-request
        if: ${{ success() }}
        uses: repo-sync/pull-request@v2
        env:
          GITHUB_TOKEN: ${{ secrets.MYWORKFLOW  }}
        with:
          GITHUB_TOKEN: ${{ secrets.MYWORKFLOW  }}
          source_branch: "test"
          destination_branch: "main"
          pr_title: ${{ github.event.head_commit.message }}
          pr_body: ${{ github.event.head_commit.message }}
          pr_label: "Staging,TestsPassed"
          pr_reviewer: "damouu"
          pr_assignee: "damouu"