name: Test

on:
  push:
    branches:
      - test

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Runing Unit/ Integration Tests
        id: run-tests
        run: echo "::set-output name=mvn-tests::mvn test -Dsurefire.useFile=false"

      - uses: actions/checkout@v2
      - name: Create an issue
        if: ${{ failure() }}
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TITLE: ${{ github.event.head_commit.message }}
          ERROR: ${{ steps.run-tests.outputs.mvn-tests }}
        with:
          assignees: ${{ github.actor }}

      - name: pull-request
        if: ${{ success() }}
        uses: repo-sync/pull-request@v2
        env:
          GITHUB_TOKEN: ${{secrets.MyWorkflow}}
        with:
          GITHUB_TOKEN: ${{ secrets.MyWorkflow  }}
          source_branch: "test"
          destination_branch: "main"
          pr_title: ${{ github.event.head_commit.message }}
          pr_body: ${{ github.event.head_commit.message }}
          pr_label: "Staging,TestsPassed"
          pr_reviewer: "damouu"
          pr_assignee: "damouu"