name: Test

on:
  push:
    branches: [ test ]

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          pr_title: "Pulling ${{ github.ref }} into main"    # Title of pull request
          pr_body: ":crown: *An automated PR*"               # Full markdown support, requires pr_title to be set
          pr_template: ".github/PULL_REQUEST_TEMPLATE.md"    # Path to pull request template, requires pr_title to be set, excludes pr_body
          pr_reviewer: "wei,worker"                          # Comma-separated list (no spaces)
          pr_assignee: "wei,worker"                          # Comma-separated list (no spaces)
          pr_label: "auto-pr"                                # Comma-separated list (no spaces)
          pr_milestone: "Milestone 1"                        # Milestone name
          pr_draft: true                                     # Creates pull request as draft
          pr_allow_empty: true                               # Creates pull request even if there are no changes
          github_token: ${{ secrets.GITHUB_TOKEN }}