name: YouTrack-Review

on:
  pull_request:
    types:
      - labeled

jobs:
  build:
    if: github.event.label.name == 'reviewing'
    runs-on: ubuntu-latest
    steps:
      - uses: bloobirds-it/action-youtrack-move@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yt-url: ${{ secrets.YOUTRACK_URL }}
          yt-token: ${{ secrets.YOUTRACK_TOKEN }}
          yt-project-id: "SD"
          yt-column-triggers: "Staging"
          yt-column-target: "Review"