name: YouTrack-Staging

on:
  pull_request_review_comment:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: bloobirds-it/action-youtrack-move@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yt-url: ${{ secrets.YOUTRACK_URL }}
          yt-token: ${{ secrets.YOUTRACK_TOKEN }}
          yt-project-id: "SD"
          yt-column-triggers: "Test"
          yt-column-target: "Staging"